# ----------------------------------------------------
# https://open.mesosphere.com/getting-started/install/
# ----------------------------------------------------

  
- hosts: mesos_cluster
  become: true
  tasks:
    - name: install mesosphere
      yum: name=http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm

    - name: install mesos
      yum: name=mesos

    - name: add docker yum repository
      copy: src=templates/docker.repo dest=/etc/yum.repos.d/docker.repo

    - name: install docker
      yum: name=docker-engine

    - name: start docker
      service: name=docker state=started


- hosts: mesos_masters
  become: true
  tasks:
    - name: install marathon
      yum: name=marathon

    - name: install zookeeper
      yum: name=mesosphere-zookeeper
  
  
    - name: set zookeeper id
      template: src=templates/myid.j2 dest=/var/lib/zookeeper/myid

    - name: set zookeeper server address
      template: src=templates/zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg backup=yes
  
  
    - name: set mesos masters addresses
      copy: src=templates/zk.mesos-masters dest=/etc/mesos/zk

    - name: set mesos master quorum
      template: src=templates/quorum.j2 dest=/etc/mesos-master/quorum

    - name: set mesos master ip
      template: src=templates/ip.j2 dest=/etc/mesos-master/ip

    - name: setup mesos master hostname
      template: src=templates/ip.j2 dest=/etc/mesos-master/hostname
  

    - name: create marathon conf dir
      file: path=/etc/marathon/conf state=directory

    - name: set marathon hostname
      template: src=templates/ip.j2 dest=/etc/marathon/conf/hostname
  
    - name: set marathon mesos addresses
      copy: src=templates/zk.mesos-masters dest=/etc/marathon/conf/master
  
    - name: set marathon addresses
      copy: src=templates/zk.marathon dest=/etc/marathon/conf/zk
  

    - name: start zookeeper
      service: name=zookeeper state=restarted
  
    - name: start mesos master
      service: name=mesos-master state=restarted

    - name: start marathon
      service: name=marathon state=restarted

 
- hosts: mesos_slaves:!mesos_masters
  become: true
  tasks:
    - name: set mesos masters addresses
      copy: src=templates/zk.mesos-masters dest=/etc/mesos/zk
  
    - name: stop mesos master
      service: name=mesos-master state=stopped

  
- hosts: mesos_slaves
  become: true
  tasks:  
    - name: set mesos slave ip
      template: src=templates/ip.j2 dest=/etc/mesos-slave/ip

    - name: set mesos slave hostname
      template: src=templates/ip.j2 dest=/etc/mesos-slave/hostname

    - name: set mesos slave containerizers
      copy: src=templates/containerizers dest=/etc/mesos-slave/containerizers

  
    - name: start mesos slave
      service: name=mesos-slave state=restarted
